FROM amazonlinux:latest

# Install dependencies
RUN yum update -y && \
    yum install -y httpd && \
    yum search wget && \
    yum install -y git && \
    yum install wget -y && \
    yum install unzip -y

# change directory
RUN cd /var/www/html

# download webfiles
RUN wget <github link to webfiles>

# unzip folder
RUN unzip main.zip

# copy files into html directory
RUN cp -r <github>/* /var/www/html/

# remove unwanted folder
RUN rm -rf <github>-main main.zip

# exposes port 80 on the container
EXPOSE 80

# set the default application that will start when the container start
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]